import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const readProjectFile = (path) =>
  readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("publishes the requested authorship, controls, and map attribution", async () => {
  const source = await readProjectFile("app/market-lab.tsx");
  const styles = await readProjectFile("app/globals.css");
  assert.match(source, /href="\.\/" aria-label="Housing Market Lab home">Housing Market Lab<\/a>/);
  assert.match(source, /href="https:\/\/desenlin\.com\/">Desen Lin<\/a>/);
  assert.match(source, /href="https:\/\/www\.fullerton\.edu\/">California State University, Fullerton<\/a>/);
  assert.match(styles, /\.header-link[^}]+color: inherit; font: inherit; text-decoration: none;/);
  assert.match(source, /Index starting month/);
  assert.match(source, /12-month growth/);
  assert.match(source, /Change from one year earlier/);
  assert.match(source, /https:\/\/tile\.openstreetmap\.org/);
  assert.match(source, /Map color gradient/);
  assert.match(source, /useState<MapPaletteKey>\("orange"\)/);
  assert.match(source, /Orange and Los Angeles Counties/);
  assert.match(source, /Prices &amp; Rents/);
  assert.match(source, /Market Conditions/);
  assert.match(source, /Metro Comparisons/);
  assert.match(source, /Latest cycle position/);
  assert.match(source, /Inventory growth vs\./);
  assert.match(source, /<TabsTrigger value="activity">Market Conditions<\/TabsTrigger>\s*<TabsTrigger value="permits">Building Permits<\/TabsTrigger>/);
  assert.match(source, /<TabsTrigger value="methods">Data &amp; methods<\/TabsTrigger>\s*<TabsTrigger value="about">About<\/TabsTrigger>/);
  assert.match(source, /<TabsTrigger value="facts">Market Brief<\/TabsTrigger>\s*<TabsTrigger value="methods">Data &amp; methods<\/TabsTrigger>/);
  assert.match(source, /Housing evidence for learning, research, and public discussion/);
  assert.match(source, /Support instruction/);
  assert.match(source, /Facilitate research/);
  assert.match(source, /Inform public discussion/);
  assert.match(source, /do not necessarily reflect the positions of California State University, Fullerton/);
  assert.match(source, /Source: \{provider\}/);
  assert.match(source, /Definition of \$\{label\}/);
  assert.match(source, /rolling three-month window/i);
  assert.match(source, /View Redfin Data Center/);
  assert.match(source, /Inventory &amp; buyer interest — Realtor\.com/);
  assert.match(source, /View Realtor\.com Data Library/);
  assert.match(source, /Flagged observations remain visible but should be reviewed before reporting/);
  assert.match(source, /Hollow points identify flagged observations/);
  assert.match(source, /Solid: trailing three-month average/);
  assert.match(source, /Dashed with points: reported monthly observations/);
  assert.match(source, /Simple moving average; no polynomial fit/);
  assert.match(source, /Market Hotness quadrant/);
  assert.match(source, /current validated release and one rollback/);
  assert.match(source, /County-level shards keep generated JSON files below 1 MB/);
  assert.match(source, /carries those dates forward from its prior compact extract/);
  assert.match(source, /Coverage identifies the newest observation in each source/);
  assert.match(source, /Final permit history/);
  assert.match(source, /Preliminary permits/);
  assert.match(source, /Technical release identifiers and fingerprints/);
  assert.match(source, /data\/acs\/latest\.json/);
  assert.match(source, /<dt>ACS context<\/dt><dd><span>Release \{acsManifest\.release\}<\/span><code>\{acsManifest\.bundle_sha256\}<\/code>/);
  assert.match(source, /href="#current-release-provenance" onClick=\{openReleaseProvenance\}/);
  assert.match(source, /<Tabs value=\{mainTab\} onValueChange=\{setMainTab\}/);
  assert.match(source, /id="current-release-provenance" className="provenance-card"/);
  assert.doesNotMatch(source, /Load Building Permits tab/);
  assert.doesNotMatch(source, /Load Housing Context tab/);
  assert.doesNotMatch(source, /bundle_sha256\.slice/);
  assert.match(source, /Gray boundaries have no data/);
  assert.match(source, /Outside city\/CDP geography/);
  assert.match(source, /Reading the maps/);
  assert.match(source, /Laguna Coast Wilderness Park/);
  assert.match(source, /No \$\{provider\} data for this/);
  assert.match(source, /Constant-dollar month/);
  assert.match(source, /Real \(inflation-adjusted\)/);
  assert.match(source, /LA-area CPI-U/);
  assert.match(source, /U\.S\. CPI-U/);
  assert.match(source, /Common deflator: U\.S\. CPI-U/);
  assert.doesNotMatch(source, /regionalDeflatorKey/);
  assert.match(source, /Add a metro comparison \(up to five\)/);
  assert.match(source, /20 largest U\.S\. metropolitan statistical areas/);
  assert.match(source, /San Jose is retained as a selected California comparator/);
  assert.match(source, /region\.population_rank \? `#\$\{region\.population_rank\} · `/);
  assert.match(source, /NativeSelectOptGroup key=\{censusRegion\} label=\{censusRegion\}/);
  assert.match(source, /aria-label={`Remove \$\{region\.name\} from comparison`}/);
  assert.doesNotMatch(source, /className=\{checked \? "metro-toggle active"/);
  assert.match(source, /nearby Riverside, CA is outlined in orange/);
  assert.match(source, /Real rent is a purchasing-power measure, not an affordability measure/);
  assert.match(source, /October 2025 uses a log-linear CPI interpolation/);
  assert.match(source, /Only derived real housing calculations fill that single gap/);
  assert.match(source, /official CPI overlays retain the gap/i);
  assert.match(source, /className="footer-emphasis" href="https:\/\/desenlin\.com\/"/);
  assert.match(source, /className="footer-emphasis" href="https:\/\/business\.fullerton\.edu\/academics\/finance"/);
  assert.match(source, /className="footer-emphasis" href="https:\/\/www\.fullerton\.edu\/"/);
  assert.match(source, /About &amp; contact/);
  assert.match(source, /function togglePlaceSelection/);
  assert.match(source, /function toggleActivityPlaceSelection/);
  assert.match(source, /aria-pressed=\{selectedIds\.includes\(item\.region\.id\)\}/);
  assert.match(source, /aria-pressed=\{activeActivitySelectedIds\.includes\(item\.region\.id\)\}/);
  assert.match(source, /Select a place from the ranking or add a comparison to display the chart/);
  assert.match(source, /Citation:<\/strong> Lin, D\. \(2026\)\. <cite>Housing Market Lab<\/cite> \[Computer software\]/);
});

test("market brief prioritizes questions, quality controls, and direct evidence", async () => {
  const source = await readProjectFile("components/facts/fact-engine-panel.tsx");
  assert.match(source, /Are home values keeping pace with local inflation\?/);
  assert.match(source, /Is residential permitting increasing\?/);
  assert.match(source, /Has metropolitan inventory shifted materially\?/);
  assert.match(source, /Are asking rents accelerating\?/);
  assert.match(source, /Release-aware quality control/);
  assert.match(source, /Questions before variables/);
  assert.match(source, /Direct evidentiary support/);
  assert.match(source, /unconstrained AI summary cannot provide this assurance/i);
  assert.match(source, /Previous market briefs/);
  assert.match(source, /Historical reconstruction/);
  assert.match(source, /correction is labeled rather than silently replacing the original record/);
});

test("repository front page includes citation and academic-use limits", async () => {
  const readme = await readProjectFile("README.md");
  assert.match(readme, /## Citation/);
  assert.match(readme, /## Academic-use disclaimer/);
  assert.match(readme, /not financial, investment, legal, valuation, or real-estate advice/i);
  assert.match(readme, /noncommercial academic-research use/i);
  assert.match(readme, /\[Desen Lin\]\(https:\/\/desenlin\.com\/\)/);
  assert.match(readme, /\[Third-party data, licensing, and attribution\]\(THIRD_PARTY_DATA\.md\)/);
  const notices = await readProjectFile("THIRD_PARTY_DATA.md");
  assert.match(notices, /do \*\*not\*\* license the data/i);
  assert.match(notices, /Zillow Research/);
  assert.match(notices, /Redfin Data Center/);
  assert.match(notices, /Realtor\.com Economic Research/);
  assert.match(notices, /Building Permits Survey/);
});

test("uses the academic website Google Analytics property", async () => {
  const layout = await readProjectFile("app/layout.tsx");
  assert.match(layout, /G-MDGMSFPEH2/);
});

test("building permits chart offers frequency-appropriate history windows", async () => {
  const source = await readProjectFile("components/permits/permit-panel.tsx");
  assert.match(source, /label="Chart range"/);
  assert.match(source, /Last 10 years/);
  assert.match(source, /Last 20 years/);
  assert.match(source, /Last 30 years/);
  assert.match(source, /Full series · since 1980/);
  assert.match(source, /Last 12 months/);
  assert.match(source, /Full series · since 2022/);
});

test("housing context stays curated and communicates ACS uncertainty", async () => {
  const source = await readProjectFile("components/acs/acs-panel.tsx");
  const page = await readProjectFile("app/market-lab.tsx");
  assert.match(page, /<TabsTrigger value="context">Housing Context<\/TabsTrigger>/);
  assert.match(source, /Six selected ACS measures/);
  assert.match(source, /not a general demographic catalog/i);
  assert.match(source, /90% margins of error retained/);
  assert.match(source, /Non-overlapping change/);
  assert.match(source, /consecutive overlapping ACS releases are intentionally omitted/i);
  assert.match(source, /Historical change is limited to cities and communities/);
  assert.match(source, /The relationship is descriptive, not causal/);
});
