import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const readProjectFile = (path) =>
  readFile(new URL(`../${path}`, import.meta.url), "utf8");

test("provides a persistent light and dark theme control", async () => {
  const layout = await readProjectFile("app/layout.tsx");
  const page = await readProjectFile("app/market-lab.tsx");
  const toggle = await readProjectFile("components/theme-toggle.tsx");
  const styles = await readProjectFile("app/globals.css");

  assert.match(layout, /attribute="class"/);
  assert.match(layout, /defaultTheme="light"/);
  assert.match(layout, /storageKey="housing-market-lab-theme"/);
  assert.match(page, /<ThemeToggle \/>/);
  assert.match(toggle, /Switch to light theme/);
  assert.match(toggle, /Switch to dark theme/);
  assert.match(styles, /\.dark \{/);
  assert.match(styles, /\.theme-toggle/);
  assert.match(styles, /--chart-grid:/);
  assert.match(styles, /--section-heading: #f0f4f7/);
  assert.match(styles, /--section-copy: #c4ced5/);
  assert.match(styles, /\.regional-intro h2 \{[^}]+color: var\(--section-heading\)/);
  assert.match(styles, /\.regional-intro > p \{[^}]+color: var\(--section-copy\)/);
  assert.match(styles, /\.provenance-card h3[^}]+color: var\(--section-heading\)/);
  assert.match(styles, /\.provenance-grid dd \{[^}]+color: var\(--detail-heading\)/);
  assert.match(styles, /\.dark \.rank-row:hover, \.dark \.rank-row\.active/);
  assert.match(styles, /\.dark \.rank-row\.selected \{[^}]+color: var\(--foreground\)/);
  assert.match(styles, /\.dark \.rank-name small[^}]+color: var\(--detail-muted\)/);
  assert.match(styles, /\.dark \.brief-evidence p \{[^}]+color: var\(--detail-copy\)/);
});

test("publishes the requested authorship, controls, and map attribution", async () => {
  const source = await readProjectFile("app/market-lab.tsx");
  const styles = await readProjectFile("app/globals.css");
  assert.match(source, /href="\.\/" aria-label="Housing Market Lab home">Housing Market Lab<\/a>/);
  assert.match(source, /href="https:\/\/desenlin\.com\/">Desen Lin<\/a>/);
  assert.match(source, /href="https:\/\/www\.fullerton\.edu\/">California State University, Fullerton<\/a>/);
  assert.match(styles, /\.header-link[^}]+color: inherit; font: inherit; text-decoration: none;/);
  assert.match(source, /Index starting month/);
  assert.match(source, /12-month growth/);
  assert.match(source, /Change from one year earlier/);
  assert.match(source, /https:\/\/tile\.openstreetmap\.org/);
  assert.match(source, /Map color gradient/);
  assert.match(source, /useState<MapPaletteKey>\("orange"\)/);
  assert.match(source, /Orange and Los Angeles Counties/);
  assert.match(source, /Prices &amp; Rents/);
  assert.match(source, /Market Conditions/);
  assert.match(source, /Metro Comparisons/);
  assert.match(source, /Latest cycle position/);
  assert.match(source, /Inventory growth vs\./);
  assert.match(source, /<TabsTrigger value="activity">Market Conditions<\/TabsTrigger>\s*<TabsTrigger value="permits">Building Permits<\/TabsTrigger>/);
  assert.match(source, /<TabsTrigger value="methods">Data &amp; methods<\/TabsTrigger>\s*<TabsTrigger value="about">About<\/TabsTrigger>/);
  assert.match(source, /<TabsTrigger value="facts">Market Brief<\/TabsTrigger>\s*<TabsTrigger value="methods">Data &amp; methods<\/TabsTrigger>/);
  assert.match(source, /A teaching-focused view of Southern California housing markets/);
  assert.match(source, /independent academic project for classroom exploration and research/);
  assert.match(source, /selected aggregate housing indicators/);
  assert.match(source, /does not contain property listings or property-level records/);
  assert.doesNotMatch(source, /instructional and research-oriented platform/);
  assert.match(source, /Support instruction/);
  assert.match(source, /Facilitate research/);
  assert.match(source, /Inform public discussion/);
  assert.match(source, /do not necessarily reflect the positions of California State University, Fullerton/);
  assert.match(source, /Source: \{provider\}/);
  assert.match(source, /Definition of \$\{label\}/);
  assert.match(source, /rolling three-month window/i);
  assert.match(source, /const activityFreshnessDate = activityDates\.at\(-1\)/);
  assert.match(source, /className="metric-title-row"[\s\S]*className="metric-freshness">Data through \{shortDate\(activityFreshnessDate\)\}<\/span>/);
  assert.match(styles, /\.metric-freshness[^}]+white-space: nowrap;/);
  assert.match(source, /View Redfin Data Center/);
  assert.match(source, /Inventory &amp; buyer interest — Realtor\.com/);
  assert.match(source, /View Realtor\.com Data Library/);
  assert.match(source, /Flagged observations remain visible but should be reviewed before reporting/);
  assert.match(source, /Hollow points identify flagged observations/);
  assert.match(source, /Solid: trailing three-month average/);
  assert.match(source, /Dashed with points: reported monthly observations/);
  assert.match(source, /Simple moving average; no polynomial fit/);
  assert.match(source, /Market Hotness quadrant/);
  assert.match(source, /current validated release and one rollback/);
  assert.match(source, /County-level shards keep generated JSON files below 1 MB/);
  assert.match(source, /carries those dates forward from its prior compact extract/);
  assert.match(source, /Coverage identifies the newest observation in each source/);
  assert.match(source, /Final permit history/);
  assert.match(source, /Preliminary permits/);
  assert.match(source, /Technical release identifiers and fingerprints/);
  assert.match(source, /data\/acs\/latest\.json/);
  assert.match(source, /<dt>ACS context<\/dt><dd><span>Release \{acsManifest\.release\}<\/span><code>\{acsManifest\.bundle_sha256\}<\/code>/);
  assert.match(source, /href="#current-release-provenance" onClick=\{openReleaseProvenance\}/);
  assert.match(source, /<Tabs value=\{mainTab\} onValueChange=\{setMainTab\}/);
  assert.match(source, /id="current-release-provenance" className="provenance-card"/);
  assert.doesNotMatch(source, /Load Building Permits tab/);
  assert.doesNotMatch(source, /Load Housing Context tab/);
  assert.doesNotMatch(source, /bundle_sha256\.slice/);
  assert.match(source, /Gray boundaries have no data/);
  assert.match(source, /Outside city\/CDP geography/);
  assert.match(source, /Reading the maps/);
  assert.match(source, /Laguna Coast Wilderness Park/);
  assert.match(source, /No \$\{provider\} data for this/);
  assert.match(source, /Constant-dollar month/);
  assert.match(source, /Real \(inflation-adjusted\)/);
  assert.match(source, /LA-area CPI-U/);
  assert.match(source, /U\.S\. CPI-U/);
  assert.match(source, /Common deflator: U\.S\. CPI-U/);
  assert.doesNotMatch(source, /regionalDeflatorKey/);
  assert.match(source, /Add a metro comparison \(up to five\)/);
  assert.match(source, /20 largest U\.S\. metropolitan statistical areas/);
  assert.match(source, /San Jose is retained as a selected California comparator/);
  assert.match(source, /region\.population_rank \? `#\$\{region\.population_rank\} · `/);
  assert.match(source, /NativeSelectOptGroup key=\{censusRegion\} label=\{censusRegion\}/);
  assert.match(source, /aria-label={`Remove \$\{region\.name\} from comparison`}/);
  assert.doesNotMatch(source, /className=\{checked \? "metro-toggle active"/);
  assert.match(source, /nearby Riverside, CA is outlined in orange/);
  assert.match(source, /Real rent is a purchasing-power measure, not an affordability measure/);
  assert.match(source, /October 2025 uses a log-linear CPI interpolation/);
  assert.match(source, /Only derived real housing calculations fill that single gap/);
  assert.match(source, /official CPI overlays retain the gap/i);
  assert.match(source, /className="footer-emphasis" href="https:\/\/desenlin\.com\/"/);
  assert.match(source, /className="footer-emphasis" href="https:\/\/business\.fullerton\.edu\/academics\/finance"/);
  assert.match(source, /className="footer-emphasis" href="https:\/\/www\.fullerton\.edu\/"/);
  assert.match(source, /About &amp; contact/);
  assert.match(source, /function togglePlaceSelection/);
  assert.match(source, /function toggleActivityPlaceSelection/);
  assert.match(source, /aria-pressed=\{selectedIds\.includes\(item\.region\.id\)\}/);
  assert.match(source, /aria-pressed=\{activeActivitySelectedIds\.includes\(item\.region\.id\)\}/);
  assert.match(source, /Select a place from the ranking or add a comparison to display the chart/);
  assert.match(source, /Citation:<\/strong> Lin, D\. \(2026\)\. <cite>Housing Market Lab<\/cite> \[Computer software\]/);
  assert.match(source, /Southern California housing data for teaching and research/);
  assert.match(source, /Housing evidence with documented methods/);
  assert.match(source, /The lab organizes selected housing indicators for teaching and academic research/);
  assert.match(source, /<CardTitle>Technical design<\/CardTitle>/);
  assert.match(source, /Provider-published files are processed into the selected measures/);
  assert.match(source, /Provider updates pass validation before release/);
  assert.doesNotMatch(source, /maintainer-initiated local import/);
  assert.doesNotMatch(source, /A small, inspectable data product/);
  assert.doesNotMatch(source, /Cost &amp; portability/);
  assert.doesNotMatch(source, /Scheduled refreshes/);
  assert.doesNotMatch(source, /GitHub Actions manages periodic data refreshes/);
  assert.match(styles, /\.deck \{[^}]+white-space: nowrap;/);
});

test("places linked provider attribution beside charts and maps", async () => {
  const page = await readProjectFile("app/market-lab.tsx");
  const attribution = await readProjectFile("components/figure-attribution.tsx");
  const acs = await readProjectFile("components/acs/acs-panel.tsx");
  const permits = await readProjectFile("components/permits/permit-panel.tsx");
  assert.match(attribution, /Data provided by Zillow Group/);
  assert.match(attribution, /Data provided by Redfin/);
  assert.match(attribution, /Realtor\.com® Economic Research/);
  assert.match(attribution, /U\.S\. Bureau of Labor Statistics/);
  assert.match(attribution, /U\.S\. Census Bureau, American Community Survey/);
  assert.match(attribution, /© .*OpenStreetMap contributors/);
  assert.match(page, /<FigureAttribution sources=\{mapSources\} boundaries basemap \/>/);
  assert.match(page, /<FigureAttribution sources=\{\[activityLens === "redfin" \? "redfin" : "realtor"\]\} \/>/);
  assert.match(acs, /<FigureAttribution sources=\{\["census-acs", "zillow"\]\} \/>/);
  assert.match(permits, /metric === "units_per_1000" \? \["census-bps", "census-acs"\] : \["census-bps"\]/);
});

test("market brief prioritizes questions, quality controls, and direct evidence", async () => {
  const source = await readProjectFile("components/facts/fact-engine-panel.tsx");
  assert.match(source, /Are home values keeping pace with local inflation\?/);
  assert.match(source, /Is residential permitting increasing\?/);
  assert.match(source, /Has metropolitan inventory shifted materially\?/);
  assert.match(source, /Are asking rents accelerating\?/);
  assert.match(source, /Release-aware quality control/);
  assert.match(source, /Questions before variables/);
  assert.match(source, /Direct evidentiary support/);
  assert.match(source, /unconstrained AI summary cannot provide this assurance/i);
  assert.match(source, /Previous market briefs/);
  assert.match(source, /Historical reconstruction/);
  assert.match(source, /correction is labeled rather than silently replacing the original record/);
});

test("market brief automation remains review gated", async () => {
  const workflow = await readProjectFile(".github/workflows/prepare-market-brief.yml");
  const generator = await readProjectFile("pipeline/prepare_market_brief.py");
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /workflow_run:/);
  assert.match(workflow, /gh pr create --draft/);
  assert.doesNotMatch(workflow, /gh pr merge/);
  assert.match(generator, /minimum_advanced_questions/);
  assert.match(generator, /No causal claim or forecast has been introduced/);
});

test("repository front page separates project licenses from third-party terms", async () => {
  const readme = await readProjectFile("README.md");
  assert.match(readme, /independent academic project for classroom exploration and research/i);
  assert.match(readme, /aggregate Southern California housing indicators/i);
  assert.match(readme, /does not contain property listings or property-level records/i);
  assert.match(readme, /## Citation/);
  assert.match(readme, /## Academic-use disclaimer/);
  assert.match(readme, /not financial, investment, legal, valuation, or real-estate advice/i);
  assert.match(readme, /intended use is instruction and academic research/i);
  assert.match(readme, /does not grant commercial-use or redistribution rights to third-party data/i);
  assert.match(readme, /\[Desen Lin\]\(https:\/\/desenlin\.com\/\)/);
  assert.match(readme, /\[licensing map\]\(LICENSES\.md\)/);
  assert.match(readme, /\[Creative Commons Attribution 4\.0 International\]\(LICENSE-CONTENT\.md\)/);
  assert.match(readme, /\[Third-party data, licensing, and attribution\]\(THIRD_PARTY_DATA\.md\)/);
  const notices = await readProjectFile("THIRD_PARTY_DATA.md");
  assert.match(notices, /do \*\*not\*\* license the data/i);
  assert.match(notices, /treats broader redistribution permission as unresolved/i);
  assert.match(notices, /Zillow Research/);
  assert.match(notices, /aggregate series at city, ZIP, and metro level/i);
  assert.match(notices, /does not collect current property listings/i);
  assert.doesNotMatch(notices, /pipeline does not retrieve Zillow files/i);
  assert.match(notices, /Redfin Data Center/);
  assert.match(notices, /Realtor\.com Economic Research/);
  assert.match(notices, /Building Permits Survey/);
});

test("uses the academic website Google Analytics property", async () => {
  const layout = await readProjectFile("app/layout.tsx");
  assert.match(layout, /G-MDGMSFPEH2/);
});

test("building permits chart offers frequency-appropriate history windows", async () => {
  const source = await readProjectFile("components/permits/permit-panel.tsx");
  assert.match(source, /label="Chart range"/);
  assert.match(source, /Last 10 years/);
  assert.match(source, /Last 20 years/);
  assert.match(source, /Last 30 years/);
  assert.match(source, /Full series · since 1980/);
  assert.match(source, /Last 12 months/);
  assert.match(source, /Full series · since 2022/);
});

test("housing context stays curated and communicates ACS uncertainty", async () => {
  const source = await readProjectFile("components/acs/acs-panel.tsx");
  const page = await readProjectFile("app/market-lab.tsx");
  assert.match(page, /<TabsTrigger value="context">Housing Context<\/TabsTrigger>/);
  assert.match(source, /Six selected ACS measures/);
  assert.match(source, /not a general demographic catalog/i);
  assert.match(source, /90% margins of error retained/);
  assert.match(source, /Non-overlapping change/);
  assert.match(source, /consecutive overlapping ACS releases are intentionally omitted/i);
  assert.match(source, /Historical change is limited to cities and communities/);
  assert.match(source, /The relationship is descriptive, not causal/);
});
