"use client";

import { MethodCard } from "@/components/method-card";
import { inflationDate, type CpiManifest } from "@/lib/inflation";

export function InflationMethods() {
  return <MethodCard title="CPI and inflation">
    <p>The Regional inflation lens in Prices &amp; Rents uses monthly, not seasonally adjusted CPI-U from the U.S. Bureau of Labor Statistics. It compares headline, core, food, groceries, dining, energy, gasoline, shelter, tenant rent, and all items excluding shelter for the LA area and the U.S. city average.</p>
    <p>Year-over-year inflation is CPI in month <em>t</em> divided by CPI in the same month one year earlier, minus one. Cumulative change is CPI in month <em>t</em> divided by CPI in the selected starting month, minus one. Changing the chart window does not change that starting month. The category table uses the latest month observed in every included series so its comparisons refer to the same period. Calculations use unrounded index values; displayed rates are rounded to one decimal place.</p>
    <p>The current Los Angeles–Long Beach–Anaheim index covers Los Angeles and Orange counties together. Its continuous history before 2018 covered the broader Los Angeles–Riverside–Orange County area; long comparisons span that geographic revision. The indexes measure price changes over time, not price-level differences between areas or separate city, ZIP-code, or county inflation. Local samples are smaller and more volatile than the national sample. <a href="https://www.bls.gov/cpi/additional-resources/geographic-revision-2018.htm" target="_blank" rel="noreferrer">BLS geographic revision</a>.</p>
    <p>Headline CPI includes food and energy; core CPI excludes both but includes shelter. Groceries and dining overlap with food, and gasoline overlaps with energy, so the displayed rates are not additive contributions to headline inflation. Shelter measures housing services, including owners’ equivalent rent, rather than home-purchase prices or mortgage payments. Tenant rent includes existing rental agreements and differs from Zillow asking rents. BLS discontinued separate local electricity and natural-gas indexes starting January 2025; its broad energy index continues. <a href="https://www.bls.gov/regions/west/news-release/averageenergyprices_losangeles.htm" target="_blank" rel="noreferrer">BLS utility-series notice</a>.</p>
    <p>Official observations remain missing where BLS did not publish them. Most selected series have an October 2025 gap from the federal appropriations lapse, while gasoline observations remain available. Inflation charts never fill gaps, and year-over-year change is unavailable if either required month is missing. Only derived real housing calculations interpolate the October 2025 headline CPI gap using the geometric midpoint of September and November. No other missing or trailing month is filled. <a href="https://www.bls.gov/cpi/additional-resources/2025-federal-government-shutdown-impact-cpi.htm" target="_blank" rel="noreferrer">BLS funding-lapse explanation</a>.</p>
    <p>The existing headline deflators remain <code>CUURS49ASA0</code> for the LA area and <code>CUUR0000SA0</code> for the United States. All twenty selected series use 1982–84=100 and are retained from January 2000. The updater retrieves each required BLS bulk file once, with API fallback batched into at most 25 series and ten-year windows. A release advances only after all required series validate. The current release records source-file or API-response fingerprints, exact series identifiers, observation coverage, and missing months below; the previous validated release is retained for rollback.</p>
  </MethodCard>;
}

export function InflationProvenance({ manifest }: { manifest: CpiManifest }) {
  return <details className="provenance-technical inflation-provenance">
    <summary>BLS CPI series coverage and retrieval sources</summary>
    <p>{Object.keys(manifest.series).length} monthly series · LA area and U.S. city average · Not seasonally adjusted</p>
    <div className="inflation-provenance-table"><table><thead><tr><th>Series</th><th>BLS identifier</th><th>Latest observation</th><th>Missing months</th></tr></thead><tbody>{Object.entries(manifest.series).map(([key, series]) => <tr key={key}><td>{series.label}</td><td><code>{series.id}</code></td><td>{inflationDate(series.latest_observation)}</td><td>{series.missing_observations.length ? series.missing_observations.map(inflationDate).join(", ") : "None"}</td></tr>)}</tbody></table></div>
    {manifest.source_files?.length ? <><p>Source fingerprints identify the decoded BLS bulk text or canonical API response used at validation; raw national files are not republished.</p><dl className="fingerprint-list">{manifest.source_files.map((source, index) => <div key={`${source.url}-${index}`}><dt><a href={source.url} target="_blank" rel="noreferrer">{source.method === "bulk" ? source.url.split("/").at(-1) : `BLS API ${source.start_year}–${source.end_year}`}</a></dt><dd><span>{source.series_ids.length} selected series · {source.method === "bulk" ? "Bulk download" : "Public API"}</span><code>{source.sha256}</code></dd></div>)}</dl></> : null}
  </details>;
}
